// ./src-tauri/src/offline/compress.rs
//! Portable raw-asset compression and transparent text readers.
//!
//! Large completed text and JSON imports are stored as gzip streams to reduce
//! disk use. Compression is atomic at the destination and validates the
//! decompressed byte count before the caller removes the source file.

use bzip2::read::BzDecoder;
use flate2::{Compression, read::GzDecoder, write::GzEncoder};
use std::fs::{self, File};
use std::io::{self, BufRead, BufReader, BufWriter};
use std::path::{Path, PathBuf};

pub const DEFAULT_COMPRESSION_THRESHOLD_BYTES: u64 = 64 * 1024 * 1024;
const BUFFER_BYTES: usize = 1024 * 1024;

pub fn is_already_compressed(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| {
            matches!(
                extension.to_ascii_lowercase().as_str(),
                "gz" | "zip" | "bz2" | "bgz"
            )
        })
}

pub fn gzip_sibling_path(path: &Path) -> PathBuf {
    let mut os_name = path.file_name().unwrap_or_default().to_os_string();
    os_name.push(".gz");
    path.with_file_name(os_name)
}

/// Resolve an asset's canonical path, its legacy uncompressed sibling, or the
/// gzip sibling generated by [`compress_if_large`].
pub fn resolve_local_asset_path(path: &Path) -> Option<PathBuf> {
    let plain_sibling = path.with_extension("");
    let candidates = [
        path.to_path_buf(),
        plain_sibling.clone(),
        gzip_sibling_path(&plain_sibling),
        gzip_sibling_path(path),
    ];
    candidates.into_iter().find(|candidate| candidate.is_file())
}

pub fn open_text_auto(path: &Path) -> Result<Box<dyn BufRead>, String> {
    let file = File::open(path).map_err(|error| format!("Open {}: {error}", path.display()))?;
    let reader: Box<dyn BufRead> = match path
        .extension()
        .and_then(|extension| extension.to_str())
        .map(str::to_ascii_lowercase)
        .as_deref()
    {
        Some("gz") | Some("bgz") => {
            Box::new(BufReader::with_capacity(BUFFER_BYTES, GzDecoder::new(file)))
        }
        Some("bz2") => Box::new(BufReader::with_capacity(BUFFER_BYTES, BzDecoder::new(file))),
        _ => Box::new(BufReader::with_capacity(BUFFER_BYTES, file)),
    };
    Ok(reader)
}

/// Stream `src` to a gzip file, replacing `dest` only after a complete write.
pub fn gzip_file_parallel_friendly(src: &Path, dest: &Path) -> Result<(), String> {
    if src == dest {
        return Err("gzip source and destination must differ".into());
    }
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("Create {}: {error}", parent.display()))?;
    }

    let temp = dest.with_extension(
        dest.extension()
            .and_then(|extension| extension.to_str())
            .map(|extension| format!("{extension}.part"))
            .unwrap_or_else(|| "part".to_string()),
    );
    let _ = fs::remove_file(&temp);

    let mut input = BufReader::with_capacity(
        BUFFER_BYTES,
        File::open(src).map_err(|error| format!("Open {}: {error}", src.display()))?,
    );
    let output =
        File::create(&temp).map_err(|error| format!("Create {}: {error}", temp.display()))?;
    let mut encoder = GzEncoder::new(
        BufWriter::with_capacity(BUFFER_BYTES, output),
        Compression::default(),
    );
    io::copy(&mut input, &mut encoder)
        .map_err(|error| format!("Compress {}: {error}", src.display()))?;
    encoder
        .finish()
        .map_err(|error| format!("Finalize {}: {error}", temp.display()))?;

    if dest.exists() {
        fs::remove_file(dest).map_err(|error| format!("Replace {}: {error}", dest.display()))?;
    }
    fs::rename(&temp, dest).map_err(|error| format!("Finalize {}: {error}", dest.display()))
}

/// Gzip an uncompressed regular file at or above `min_bytes`.
///
/// The original is removed only after the resulting gzip stream decompresses
/// to exactly the original byte length.
pub fn compress_if_large(path: &Path, min_bytes: u64) -> Result<PathBuf, String> {
    if is_already_compressed(path) {
        return Ok(path.to_path_buf());
    }
    let source_size = fs::metadata(path)
        .map_err(|error| format!("Inspect {}: {error}", path.display()))?
        .len();
    if source_size < min_bytes {
        return Ok(path.to_path_buf());
    }

    let compressed = gzip_sibling_path(path);
    gzip_file_parallel_friendly(path, &compressed)?;

    let mut decoder = GzDecoder::new(
        File::open(&compressed)
            .map_err(|error| format!("Open {}: {error}", compressed.display()))?,
    );
    let verified_size = io::copy(&mut decoder, &mut io::sink())
        .map_err(|error| format!("Verify {}: {error}", compressed.display()))?;
    if verified_size != source_size {
        let _ = fs::remove_file(&compressed);
        return Err(format!(
            "Compression verification failed for {}: expected {source_size} bytes, got {verified_size}",
            path.display()
        ));
    }

    fs::remove_file(path).map_err(|error| format!("Remove {}: {error}", path.display()))?;
    Ok(compressed)
}
